import type {
  ActivityItem,
  Client,
  NotificationItem,
  Project,
  Task,
  UserProfile,
} from "@/lib/types";

export const currentUser: UserProfile = {
  id: "user-1",
  name: "Lina Carter",
  email: "lina@aether.studio",
  role: "admin",
  avatarUrl: "https://api.dicebear.com/9.x/glass/svg?seed=Lina%20Carter",
  title: "Creative Operations Lead",
  activity: "Reviewing sprint risk and client escalations.",
  availability: "Focused",
};

export const users: UserProfile[] = [
  currentUser,
  {
    id: "user-2",
    name: "Omar Reyes",
    email: "omar@aether.studio",
    role: "manager",
    avatarUrl: "https://api.dicebear.com/9.x/glass/svg?seed=Omar%20Reyes",
    title: "Account Manager",
    activity: "Preparing Q2 campaign review.",
    availability: "Available",
  },
  {
    id: "user-3",
    name: "Nia Walker",
    email: "nia@aether.studio",
    role: "team_member",
    avatarUrl: "https://api.dicebear.com/9.x/glass/svg?seed=Nia%20Walker",
    title: "Senior Brand Designer",
    activity: "Finalizing motion deck.",
    availability: "In review",
  },
  {
    id: "user-4",
    name: "Theo Kim",
    email: "theo@aether.studio",
    role: "team_member",
    avatarUrl: "https://api.dicebear.com/9.x/glass/svg?seed=Theo%20Kim",
    title: "Frontend Engineer",
    activity: "Shipping portal interactions.",
    availability: "Focused",
  },
  {
    id: "user-5",
    name: "Maya Singh",
    email: "maya@aether.studio",
    role: "manager",
    avatarUrl: "https://api.dicebear.com/9.x/glass/svg?seed=Maya%20Singh",
    title: "Delivery Manager",
    activity: "Balancing workloads for launch week.",
    availability: "Available",
  },
];

export const clients: Client[] = [
  {
    id: "client-1",
    companyName: "Northstar Atelier",
    contactName: "Ari Bennett",
    email: "ari@northstar.co",
    phone: "+1 415 555 0104",
    status: "active",
    linkedProjectIds: ["project-1", "project-2"],
    notes: "High-touch luxury brand. Prefers asynchronous updates and crisp visual reporting.",
    industry: "Luxury retail",
    spend: "$84,000",
  },
  {
    id: "client-2",
    companyName: "Pulsewave Labs",
    contactName: "Eden Price",
    email: "eden@pulsewave.io",
    phone: "+1 646 555 0144",
    status: "lead",
    linkedProjectIds: ["project-3"],
    notes: "Exploring a product launch sprint and retainer packaging.",
    industry: "AI software",
    spend: "$32,000",
  },
  {
    id: "client-3",
    companyName: "Velora Homes",
    contactName: "Marc Ellis",
    email: "marc@velora.com",
    phone: "+1 213 555 0198",
    status: "active",
    linkedProjectIds: ["project-4"],
    notes: "Needs weekly asset approvals and stakeholder digest.",
    industry: "Real estate",
    spend: "$56,500",
  },
  {
    id: "client-4",
    companyName: "Fable Roasters",
    contactName: "Joanna Cole",
    email: "joanna@fable.coffee",
    phone: "+1 503 555 0131",
    status: "inactive",
    linkedProjectIds: [],
    notes: "Former seasonal campaign client. Good reactivation candidate.",
    industry: "Food and beverage",
    spend: "$14,800",
  },
];

export const projects: Project[] = [
  {
    id: "project-1",
    name: "Northstar Concierge Portal",
    clientId: "client-1",
    description: "Premium client portal redesign with CRM integration and onboarding motion.",
    status: "active",
    deadline: "2026-04-19",
    progress: 74,
    budget: "$28,000",
    health: "Healthy",
    teamMemberIds: ["user-1", "user-3", "user-4"],
  },
  {
    id: "project-2",
    name: "Northstar Summer Campaign",
    clientId: "client-1",
    description: "Launch system spanning paid social, email, and influencer creative.",
    status: "at_risk",
    deadline: "2026-04-12",
    progress: 58,
    budget: "$38,000",
    health: "Watch",
    teamMemberIds: ["user-2", "user-3", "user-5"],
  },
  {
    id: "project-3",
    name: "Pulsewave Product Narrative",
    clientId: "client-2",
    description: "Pitch positioning and launch landing page concept sprint.",
    status: "planning",
    deadline: "2026-05-01",
    progress: 22,
    budget: "$16,000",
    health: "Healthy",
    teamMemberIds: ["user-1", "user-2", "user-4"],
  },
  {
    id: "project-4",
    name: "Velora Sales Enablement",
    clientId: "client-3",
    description: "Interactive showroom and sales collateral system for new development launch.",
    status: "active",
    deadline: "2026-04-27",
    progress: 67,
    budget: "$24,000",
    health: "Healthy",
    teamMemberIds: ["user-2", "user-4", "user-5"],
  },
];

export const tasks: Task[] = [
  {
    id: "task-1",
    title: "Finalize concierge onboarding storyboard",
    description: "Align motion pacing with premium welcome flow and handoff states.",
    status: "review",
    priority: "high",
    assigneeId: "user-3",
    dueDate: "2026-04-08",
    projectId: "project-1",
    tags: ["Motion", "UX"],
    attachments: 3,
    comments: [
      {
        id: "comment-1",
        authorId: "user-1",
        message: "Keep the first transition softer to match the brand tone.",
        createdAt: "2026-04-04T14:30:00.000Z",
      },
    ],
  },
  {
    id: "task-2",
    title: "Map summer campaign launch dependencies",
    description: "Sequence paid, organic, and influencer deliverables across the launch week.",
    status: "in_progress",
    priority: "urgent",
    assigneeId: "user-5",
    dueDate: "2026-04-06",
    projectId: "project-2",
    tags: ["Planning", "Launch"],
    attachments: 1,
    comments: [],
  },
  {
    id: "task-3",
    title: "Build modular testimonial section",
    description: "Reusable component blocks for brand proof and concierge quotes.",
    status: "todo",
    priority: "medium",
    assigneeId: "user-4",
    dueDate: "2026-04-11",
    projectId: "project-1",
    tags: ["Frontend"],
    attachments: 0,
    comments: [],
  },
  {
    id: "task-4",
    title: "Draft Pulsewave narrative angle options",
    description: "Present three directions with headline system and tone notes.",
    status: "done",
    priority: "high",
    assigneeId: "user-2",
    dueDate: "2026-04-03",
    projectId: "project-3",
    tags: ["Copy", "Strategy"],
    attachments: 2,
    comments: [],
  },
  {
    id: "task-5",
    title: "Capture stakeholder approval notes",
    description: "Summarize all requested edits from the Velora review call.",
    status: "review",
    priority: "medium",
    assigneeId: "user-2",
    dueDate: "2026-04-07",
    projectId: "project-4",
    tags: ["Client"],
    attachments: 0,
    comments: [],
  },
  {
    id: "task-6",
    title: "Refine homepage animation states",
    description: "Polish hover, drag, and page transition motion for the portal shell.",
    status: "in_progress",
    priority: "high",
    assigneeId: "user-4",
    dueDate: "2026-04-09",
    projectId: "project-1",
    tags: ["Motion", "Frontend"],
    attachments: 4,
    comments: [],
  },
  {
    id: "task-7",
    title: "Assemble campaign performance recap",
    description: "Build the weekly analytics board for Northstar.",
    status: "todo",
    priority: "low",
    assigneeId: "user-1",
    dueDate: "2026-04-15",
    projectId: "project-2",
    tags: ["Reporting"],
    attachments: 0,
    comments: [],
  },
];

export const activityFeed: ActivityItem[] = [
  {
    id: "activity-1",
    actor: "Maya Singh",
    message: "moved task 'Map summer campaign launch dependencies' into In Progress",
    context: "Northstar Summer Campaign",
    timestamp: "10 minutes ago",
  },
  {
    id: "activity-2",
    actor: "Theo Kim",
    message: "uploaded 4 interaction studies",
    context: "Northstar Concierge Portal",
    timestamp: "42 minutes ago",
  },
  {
    id: "activity-3",
    actor: "Omar Reyes",
    message: "added client note on stakeholder tone preference",
    context: "Velora Homes",
    timestamp: "1 hour ago",
  },
  {
    id: "activity-4",
    actor: "Lina Carter",
    message: "approved Q2 resourcing plan",
    context: "Admin control center",
    timestamp: "Today",
  },
];

export const notifications: NotificationItem[] = [
  {
    id: "notification-1",
    title: "New mention from Maya",
    body: "Please review the launch dependency board before 3 PM.",
    kind: "mention",
    read: false,
    createdAt: "2m ago",
  },
  {
    id: "notification-2",
    title: "Task status changed",
    body: "Onboarding storyboard moved to Review.",
    kind: "task",
    read: false,
    createdAt: "24m ago",
  },
  {
    id: "notification-3",
    title: "Project risk updated",
    body: "Northstar Summer Campaign is now flagged as Watch.",
    kind: "project",
    read: true,
    createdAt: "1h ago",
  },
];

export const throughputData = [
  { label: "Week 1", completed: 14, active: 9 },
  { label: "Week 2", completed: 19, active: 11 },
  { label: "Week 3", completed: 22, active: 10 },
  { label: "Week 4", completed: 27, active: 12 },
  { label: "Week 5", completed: 24, active: 8 },
  { label: "Week 6", completed: 31, active: 13 },
];

export const focusBreakdown = [
  { name: "Client work", value: 46 },
  { name: "Internal ops", value: 18 },
  { name: "Creative reviews", value: 24 },
  { name: "Reporting", value: 12 },
];
